image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.0"
  ANDROID_SDK_TOOLS: "27.0.3"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update && apt upgrade -y && apt install -y curl bsdtar && rm -rf /var/lib/apt/lists/*
  - mkdir -p /opt/android-sdk
  - mkdir -p /opt/android-ndk
  - curl https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip | bsdtar -xvpf- -C /opt/android-sdk
  - curl https://dl.google.com/android/repository/android-ndk-r17-linux-x86_64.zip | bsdtar -xvpf- -C /opt/android-ndk
  - export ANDROID_SDK_HOME="/opt/android-sdk"
  - export ANDROID_HOME="$ANDROID_SDK_HOME"
  - export NDK_HOME="/opt/android-ndk/android-ndk-r17"
  - export ANDROID_NDK="$NDK_HOME"
  - export ANDROID_NDK_HOME="$NDK_HOME"
  - export ANDROID_NDK_ROOT="$NDK_HOME"
  - chmod -R 777 ${NDK_HOME}
  - chmod -R 777 ${ANDROID_HOME}
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}"

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
