image: openjdk:8-jdk

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - android-sdk
    - android-ndk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.0"
  ANDROID_SDK_TOOLS: "27.0.3"
  ANDORID_SDK_VERSION: "3859397"
  ANDROID_NDK_VERSION: "17"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update && apt upgrade -y && apt install -y curl bsdtar make file gcc && rm -rf /var/lib/apt/lists/*
  - mkdir -p $PWD/android-sdk
  - mkdir -p $PWD/android-ndk
  - >
    if [ ! -d "./android-sdk/bin" ]; then
      curl https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_VERSION}.zip
      | bsdtar -xpf- -C $PWD/android-sdk
    ; fi
  - >
    if [ ! -d "./android-sdk/bin" ]; then
      curl https://dl.google.com/android/repository/android-ndk-r${ANDROID_NDK_VERSION}-linux-x86_64.zip
      | bsdtar -xpf- -C $PWD/android-ndk
    ; fi
  - export ANDROID_SDK_HOME="$PWD/android-sdk"
  - export ANDROID_HOME="$ANDROID_SDK_HOME"
  - export NDK_HOME="$PWD/android-ndk/android-ndk-r${ANDROID_NDK_VERSION}"
  - export ANDROID_NDK="$NDK_HOME"
  - export ANDROID_NDK_HOME="$NDK_HOME"
  - export ANDROID_NDK_ROOT="$NDK_HOME"
  - chmod -R 777 ${NDK_HOME}
  - chmod -R 777 ${ANDROID_HOME}
  - export PATH="${ANDROID_SDK_HOME}/tools/bin:${ANDROID_SDK_HOME}/platform-tools:${ANDROID_NDK_HOME}:${PATH}"
  - echo y | sdkmanager "build-tools;${ANDROID_SDK_TOOLS}" "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}"

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
